version: "0.1.0"
client:
  api_id: # Your API ID
  api_hash: # Your API Hash
  phone_number: # Your phone number
  cloud_password: # Your 2FA password if you have it
user_ids: # Users IDs list
  -
  -
  -